inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: "3.2.0"
  Exclude:
    - "bin/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent

Layout/LineLength:
  Enabled: false

Style/NumericLiterals:
  Strict: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: "()"
    "%": "{}"
    "%i": "()"
    "%w": "()"

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/EvenOdd:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true
  EnforcedStyleForExponentOperator: space

Lint/SuppressedException:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

Style/DoubleNegation:
  Enabled: false

Lint/FormatParameterMismatch:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/BeEq:
  Enabled: false
